### ISSUE TITLE
Clicking on Shopping crashes website

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/CapstoneProject#101] opened 2022-04-06 18:00 UTC
https://user-images.githubusercontent.com/228704/162038827-f3e86c28-e55b-4ea8-8ea6-4dff1a695046.mp4

**Comment by Nicolas-A-Becker** [comment] 2022-04-07 21:26
Sorry about this. I had incorrectly run migrations when pulling the code onto the server so the database was not prepped correctly. That issue is now fixed and is not a bug with the code.

**Closed by Nicolas-A-Becker** 2022-04-07 21:26 UTC
Labels: bug
