### ISSUE TITLE
Checkmarks always become un-checked

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/CapstoneProject#87] opened 2022-03-01 01:34 UTC
Trying to mark them as Done, but cannot.

https://user-images.githubusercontent.com/228704/156087886-3c751862-80c7-4197-a87c-867c4a1fc4cc.mp4

**Comment by OMHavec** [comment] 2022-03-17 21:21
duplicate of #90

**Closed by OMHavec** 2022-03-17 21:21 UTC
Labels: bug
