### ISSUE TITLE
 When clicking contacts,  throws error exception

### ISSUE THREAD

**Issue by BranavanKalapathy23** [SCCapstone/CapstoneProject#128] opened 2022-04-17 19:56 UTC
https://user-images.githubusercontent.com/54036018/163730159-49d56ba3-7aa8-41f2-a00a-e1052320a125.mp4

**Comment by Nicolas-A-Becker** [comment] 2022-04-19 15:37
duplicate of issue #123

**Closed by Nicolas-A-Becker** 2022-04-19 15:37 UTC
Labels: bug
