### ISSUE TITLE
Login should be clear that only google sign is allowed

### ISSUE THREAD

**Issue by ICanNomNoms** [SCCapstone/CapstoneProject#83] opened 2022-02-28 23:26 UTC
When clicking on sign in nothing happens, so I can not test that anything else works.

https://user-images.githubusercontent.com/44646798/156075939-187e0c02-1ec3-4470-86f1-c5ff84d34570.mov

**Comment by josemvidal** [comment] 2022-03-01 01:22
Me too.

I was able to sign in by clicking the "sign in with google".

**Comment by Nicolas-A-Becker** [comment] 2022-03-01 15:29
@josemvidal For security and privacy purposes we decided to focus on only using Google Sign-in. This way we wouldn't be responsible for passwords and authentication in that regard, to increase user safety, as we are very inexperienced with handling sensitive information and security. If you believe that adding a local sign-in option would be beneficial we can work on adding that in and managing local authentication tools.

**Comment by josemvidal** [comment] 2022-03-02 20:55
Then, the login page should be clear about it. That big whitespace there implies that a login prompt will appear.

**Comment by OMHavec** [comment] 2022-03-17 21:22
duplicate of #92

**Closed by OMHavec** 2022-03-17 21:22 UTC
Labels: bug
