### ISSUE TITLE
Clicking on Chores crashes the app

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/CapstoneProject#103] opened 2022-04-06 18:03 UTC
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/228704/162039285-8f1d4e85-eff2-487e-a642-54bafd0385e9.png">

**Comment by Nicolas-A-Becker** [comment] 2022-04-07 21:25
Sorry about this. I had incorrectly run migrations when pulling the code onto the server so the database was not prepped correctly. That issue is now fixed and is not a bug with the code.

**Closed by Nicolas-A-Becker** 2022-04-07 21:25 UTC
Labels: bug
