### ISSUE TITLE
Clicking on Calendar brings up a 404

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/CapstoneProject#102] opened 2022-04-06 18:01 UTC
https://user-images.githubusercontent.com/228704/162038928-141056bd-520f-4c7b-9d43-b82223508a7c.mp4

**Comment by Nicolas-A-Becker** [comment] 2022-04-07 21:26
Sorry about this. I had incorrectly run migrations when pulling the code onto the server so the database was not prepped correctly. That issue is now fixed and is not a bug with the code.

**Closed by Nicolas-A-Becker** 2022-04-07 21:26 UTC
Labels: bug
