### ISSUE TITLE
Shopping and Chores cannot be deleted, and capped at 10

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/CapstoneProject#88] opened 2022-03-01 01:35 UTC
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/228704/156088052-33f77e56-2a37-4e8d-8ca6-289e0cb885e9.png">

**Comment by OMHavec** [comment] 2022-03-03 22:39
They can be deleted by clearing each input field manually. The cap of 10 items was intentional.

**Comment by OMHavec** [comment] 2022-03-17 21:22
duplicate of #91

**Closed by OMHavec** 2022-03-17 21:22 UTC
Labels: bug
